kind: kind: Service                                            # Defines to create Service type Object
apiVersion: v1
metadata:
  name:  suveerbuilds
  labels:
    app: suveerbuilds
spec:
  ports:
  - port: 8080                                                 # Containers port exposed
    targetPort:  80                                            # Pods port 
    nodePort: 31200
  selector:
    app: suveerbuilds                                          # Apply this service to any pods which has the specific label
  type: LoadBalancer                                           # Specifies the service type i.e ClusterIP or NodePort